### ISSUE TITLE
Add examples of using the streaming API

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s-demo#3]
At present, we only have examples of how to use the twitter rest client. It would be cool to have examples on how to use the twitter streaming client.

**Comment by shiv4nsh** [comment]
@DanielaSfregola : Is this being done by someone ? If not Can you assign this to me ? Thanks

**Comment by DanielaSfregola** [comment]
All yours @shiv4nsh! Thank you for your collaboration.

Note that if other people want to do this as well, this can be done. The More examples, the better!

**Comment by DanielaSfregola** [comment]
We now have a few examples on the streaming API.

Closing it.
