### ISSUE TITLE
Error and Limit reach handle

### ISSUE THREAD

**Issue by MyraBaba** [DanielaSfregola/twitter4s-demo#4]
Hi,

We are playing with Twitter4s-demo.  

How we can detect that we reached our limit ?  So we can change our auth keys. ?

thx

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba, at present you can only look at the `Future` returned. If rate is reached the TwitterException will make the future fail accordingly. Alternatively, you also have an endpoint for rate limits.

We do have a plan to improve the support on info about rate limits (see ticket https://github.com/DanielaSfregola/twitter4s/issues/80) but the functionality is not there yet.

**Comment by DanielaSfregola** [comment]
Rate Limits support is now available in twitter4s 5.0
