### ISSUE TITLE
"*" land = xx  all tweets

### ISSUE THREAD

**Issue by MyraBaba** [DanielaSfregola/twitter4s-demo#5]
Hi,

in python api we can do 👍 
`                                resp = t.search.tweets(q="*", lang=langs[language], count=page_size, last_id=last_id, until=start_date, blah=str(uuid.uuid4()))
`

q="*"  we can use.

But when we try in demo code:

`searchTweets("*").map { tweets =>
    println(s"Downloaded ${tweets.size} tweets")
    toFileAsJson("src/main/resources/tweets/scalax3.json", tweets)
    println(s"Tweets saved to file $filename")
  }`

its not working ..

any idea.?

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
I am not an expert of tweepy....can you give me more context of what you are trying to do? are you using the rest api (i.e.: searching the tweets in the past) or the streaming api (i.e.: receiving the tweets as they happen)?

Also, where did you get `searchTweets`...?

**Comment by MyraBaba** [comment]
I want to make a search “*”  in a lang=xx  

it means all tweets from that language.  query = “*”   .  its work on the python. So we can collect lots of tweets from a language.

using the rest search api.

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
have a look at `searchTweet` function of the TwitterRestClient (see http://danielasfregola.github.io/twitter4s/4.0.1/api/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient for more details).

Cheers,
D.

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,I believe you are looking for the `searchTweet` function of the TwitterRestClient. See scaladoc for more info: http://danielasfregola.github.io/twitter4s/4.0.1/api/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient

Cheers,
Daniela

**Comment by MyraBaba** [comment]
yes I am playing with the demo code:

  searchTweets("*").map { tweets =>
 *  is not working.




package rest

import com.danielasfregola.twitter4s.TwitterRestClient
import com.danielasfregola.twitter4s.entities.Tweet
import com.danielasfregola.twitter4s.entities.enums.{Language, ResultType}
import com.typesafe.config.ConfigFactory
import utils.FileSupport

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future


object SearchAndSaveTweets extends App with FileSupport {

  // TODO - Make sure to define your consumer and access tokens!
  val client = TwitterRestClient()

  def searchTweets(query: String, max_id: Option[Long] = None): Future[Seq[Tweet]] = {
    def extractNextMaxId(params: Option[String]): Option[Long] = {
      //example: "?max_id=658200158442790911&q=%23scala&include_entities=1&result_type=mixed"
      params.getOrElse("").split("&").find(_.contains("max_id")).map(_.split("=")(1).toLong)
    }

    client.searchTweet(query, count = 2, result_type = ResultType.Recent,  max_id = max_id , language = Option(Language.Turkish) ).flatMap { result =>
        val nextMaxId = extractNextMaxId(result.search_metadata.next_results)
        val tweets = result.statuses
        if (tweets.nonEmpty) searchTweets(query, nextMaxId).map(_ ++ tweets)
        else Future(tweets.sortBy(_.created_at))
      } recover { case _ => Seq.empty }
  }

  val filename = {
    val config = ConfigFactory.load()
    config.getString("tweets.scalax")
  }

  searchTweets("*").map { tweets =>
    println(s"Downloaded ${tweets.size} tweets")
    toFileAsJson("src/main/resources/tweets/scalax4.json", tweets)
    println(s"Tweets saved to file $filename")
  }

}

**Comment by DanielaSfregola** [comment]
` *  is not working.`
Do you get an error? What does it happen?

**Comment by MyraBaba** [comment]
when I put *  in the query it says nothing. saved empty json file. like :

Downloaded 0 tweets
Tweets saved to file src/main/resources/tweets/scalax.json

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
it is probably a bug of the client, I'll look into it asap! Cheers

**Comment by MyraBaba** [comment]
thx

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba, thank you for raising this issue.
I have found the bug and it will be fixed in the next release (see https://github.com/DanielaSfregola/twitter4s/issues/91 for more details).

Cheers,
D.

**Comment by MyraBaba** [comment]
thanks..  I am waiting :)  I want to port to scala with your twitter4s.  Currently using python .

thx

**Comment by DanielaSfregola** [comment]
Hi @MyraBaba,
the fix has been released in twitter4s 4.1!

Please do let me know if this is still not working as expected. 

Cheers,
D.

**Comment by MyraBaba** [comment]
Ok I will test and let you know..

**Comment by MyraBaba** [comment]
Hi Daniela,


I tested it now  with query=“*”  with language=Option(Language.xxxx)  all is ok now.

It is working now.

thx..
